apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-app
  namespace: api-ns
spec:
  selector:
    matchLabels:
      app: poi-app
  template:
    metadata:
      labels:
        app: poi-app
        aadpodidbinding: poi-id 
    spec:        
      containers:
      - name: poi
        image: registryysu9847.azurecr.io/tripinsights/poi:1.0        
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: SQL_SERVER
          value: "sqlserverysu9847.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: WEB_PORT
          value: "80"
        ports: 
        - containerPort: 80
          name: poi
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-podid"
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: api-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: poi-app
