kind: Role 
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-readonly
  namespace: api-ns
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]