kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-readonly
  namespace: web-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-readonly
subjects:
- kind: Group
  namespace: api-ns
  name: c47f024d-0e27-4f86-81c6-979c2bbc2121