# This is a SecretProviderClass example using aad-pod-identity to access the key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-podid
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"               # Set to true for using aad-pod-identity to access your key vault
    keyvaultName: kv-aks-team-2       # Set to the name of your key vault
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects: | 
      array: 
        - | 
          objectName: SQLPWD
          objectType: secret             # object types: secret, key, or cert
        - | 
          objectName: SQLUSR
          objectType: secret
    tenantId: 07be73d2-15e2-470a-a651-2365d6cd8898                # The tenant ID of the key vault
