apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-app
  namespace: api-ns
  labels:
    aadpodidbinding: trips-id
spec:
  selector:
    matchLabels:
      app: trips-app
  template:
    metadata:
      labels:
        app: trips-app
    spec:        
      containers:
      - name: trips
        image: registryysu9847.azurecr.io/tripinsights/trips:1.0
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: secrets-store01-inline
              key: SQLUSR
              optional: false 
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-store01-inline
              key: SQLPWD
              optional: false
        - name: SQL_SERVER
          value: "sqlserverysu9847.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: PORT
          value: "80"
        ports: 
        - containerPort: 80
          name: trips
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-podid"

---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
  namespace: api-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: trips-app
