apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-app
  namespace: web-ns
spec:
  selector:
    matchLabels:
      app: tripviewer-app
  template:
    metadata:
      labels:
        app: tripviewer-app
    spec:        
      containers:
      - name: tripviewer
        image: registryysu9847.azurecr.io/tripinsights/tripviewer:1.0
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: http://userprofile-service.api-ns.svc.cluster.local:80
        - name: TRIPS_API_ENDPOINT
          value: http://trips-service.api-ns.svc.cluster.local:80
        ports: 
        - containerPort: 80
          name: tripviewer
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
  namespace: web-ns
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tripviewer-app
