apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-app
spec:
  selector:
    matchLabels:
      app: userprofile-app
  template:
    metadata:
      labels:
        app: userprofile-app
    spec: 
      containers:       
      - name: userprofile
        image: registryysu9847.azurecr.io/tripinsights/userprofile:1.0
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: username
              optional: false 
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: password
              optional: false 
        - name: SQL_SERVER
          value: "sqlserverysu9847.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: PORT
          value: "80"
        ports: 
        - containerPort: 80
          name: userprofile
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: userprofile-app
