apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-app
  namespace: api-ns
spec:
  selector:
    matchLabels:
      app: user-java-app
  template:
    metadata:
      labels:
        app: user-java-app
        aadpodidbinding: user-java-id
    spec:        
      containers:
      - name: user-java
        image: registryysu9847.azurecr.io/tripinsights/user-java:1.0      
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true
        env:        
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: SQL_SERVER
          value: "sqlserverysu9847.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: PORT
          value: "80"
        ports: 
        - containerPort: 80
          name: user-java
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-podid"
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  namespace: api-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: user-java-app
