apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-app
  namespace: api-ns
spec:
  selector:
    matchLabels:
      app: userprofile-app
  template:
    metadata:
      labels:
        app: userprofile-app
        aadpodidbinding: userprofile-id 
    spec: 
      containers:       
      - name: userprofile
        image: registryysu9847.azurecr.io/tripinsights/userprofile:1.0
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true
        env:
        - name: SQL_SERVER
          value: "sqlserverysu9847.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: PORT
          value: "80"
        ports: 
        - containerPort: 80
          name: userprofile
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-podid"
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  namespace: api-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: userprofile-app
